-- Passwords are hashed using BCrypt algorithm https://bcrypt-generator.com/
-- Passwords for all users are:
--
-- Script generates database for student-service
-- It generates:
--	- 50 students
--	- 20 users
--
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------ Inserting students ------------------------------------------------------------------------------------------
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (1, 'Lorrine', 'Thiel', 'Willa', 'A6 1/2012', '2000-02-15', 'Beograd', 'Bulevar Milutina Milankovića', 23, '0646030521', 'student1@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (2, 'Abel', 'Volkman', 'Alejandrina', 'S2 2/2020', '2000-06-06', 'Beograd', 'Cara Dušana', 19, '0646658381', 'student2@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (3, 'Lindsay', 'Hayes', 'Darell', 'EF 3/2013', '2000-05-05', 'Beograd', 'Savska', 13, '0642474152', 'student3@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (4, 'Maybell', 'Murray', 'Gerry', 'DV 4/2016', '2000-03-20', 'Beograd', 'Nemanjina', 74, '0641671486', 'student4@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (5, 'Haywood', 'Dickinson', 'Elwood', 'XI 5/2018', '2000-09-25', 'Beograd', 'Južni bulevar', 21, '0640332739', 'student5@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (6, 'Paris', 'Lehner', 'Daine', 'Z4 6/2011', '2000-07-07', 'Beograd', 'Bulevar kneza Aleksandra Karađorđevića', 67, '0642610577', 'student6@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (7, 'Melani', 'Lockman', 'Son', 'ZR 7/2014', '2000-05-27', 'Beograd', 'Dr Milutina Ivkovića', 62, '0643845037', 'student7@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (8, 'Kyung', 'Kunze', 'Emmett', 'GI 8/2011', '2000-03-26', 'Beograd', 'Vojvode Stepe', 86, '0648221853', 'student8@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (9, 'Christi', 'Hauck', 'Jarod', 'A1 9/2016', '2000-02-18', 'Beograd', 'Jurija Gagarina', 32, '0646166625', 'student9@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (10, 'Bradford', 'Cummings', 'Rachele', 'M2 10/2014', '2000-08-27', 'Beograd', 'Gandijeva', 63, '0642330668', 'student10@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (11, 'Mitzi', 'Jerde', 'Geraldo', 'A1 11/2016', '2000-02-13', 'Beograd', 'Pariske komune', 40, '0641492109', 'student11@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (12, 'Vonda', 'Farrell', 'Hung', 'A4 12/2013', '2000-05-06', 'Beograd', 'Bulevar Nikole Tesle', 82, '0646805067', 'student12@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (13, 'Edwardo', 'Gerhold', 'Myung', 'G1 13/2012', '2000-10-25', 'Beograd', 'Bulevar Zorana Đinđića', 74, '0643612704', 'student13@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (14, 'Shirley', 'Stracke', 'Elliot', 'O1 14/2016', '2000-04-14', 'Beograd', 'Milentija Popovića', 46, '0647627788', 'student14@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (15, 'Jesse', 'Armstrong', 'Sharan', 'DA 15/2021', '2000-06-04', 'Beograd', 'Bulevar Despota Stefana', 17, '0640572138', 'student15@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (16, 'Many', 'Hessel', 'Lori', 'E1 16/2012', '2000-02-27', 'Beograd', 'Dimitrija Tucovića', 3, '0641066767', 'student16@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (17, 'Gene', 'Wintheiser', 'Johanna', 'EF 17/2011', '2000-04-16', 'Beograd', 'Žička', 27, '0643550587', 'student17@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (18, 'Mozella', 'Frami', 'Jon', 'ZZ 18/2016', '2000-07-22', 'Beograd', 'Višnjička', 32, '0646222739', 'student18@gmail.com', 3);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (19, 'Arminda', 'Christiansen', 'Joline', 'BI 19/2017', '2000-07-10', 'Beograd', 'Jovanke Radaković', 81, '0646596077', 'student19@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (20, 'Lynwood', 'DuBuque', 'Earnest', 'XH 20/2017', '2000-01-09', 'Beograd', 'Vitanovačka', 67, '0641398384', 'student20@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (21, 'Merlin', 'Kutch', 'Tawny', 'SE 21/2014', '2000-09-21', 'Beograd', 'Kumodraška', 6, '0640179619', 'student21@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (22, 'Margret', 'Wilderman', 'Sung', 'A3 22/2016', '2000-08-27', 'Beograd', 'Neznanog junaka', 70, '0641133646', 'student22@gmail.com', 3);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (23, 'Nohemi', 'Weber', 'Edgar', 'MH 23/2011', '2000-03-23', 'Beograd', 'Braće Jerković', 64, '0644641550', 'student23@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (24, 'Israel', 'Green', 'Karisa', 'E4 24/2016', '2000-03-16', 'Beograd', 'Svetozara Radojčića', 69, '0642576787', 'student24@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (25, 'Dorothy', 'Dach', 'Walter', 'SS 25/2021', '2000-08-19', 'Beograd', 'Mite Ružića', 85, '0641566071', 'student25@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (26, 'Ali', 'VonRueden', 'Korey', 'G1 26/2021', '2000-03-07', 'Beograd', 'Milana Rakića', 23, '0641465642', 'student26@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (27, 'Osvaldo', 'McCullough', 'Lacey', 'XZ 27/2018', '2000-07-03', 'Beograd', 'Bulevar vojvode Mišića', 6, '0647426617', 'student27@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (28, 'Virgilio', 'Terry', 'Kirby', 'AJ 28/2020', '2000-08-18', 'Beograd', 'Bulevar Patrijarha Pavla', 61, '0643712743', 'student28@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (29, 'Cyndy', 'Mraz', 'Allison', 'DH 29/2011', '2000-09-10', 'Beograd', 'Požeška', 83, '0648668298', 'student29@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (30, 'Chong', 'Pagac', 'Agustin', 'M3 30/2014', '2000-10-25', 'Beograd', 'Radnička', 68, '0644756667', 'student30@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (31, 'Karina', 'Wiegand', 'Marcy', 'XO 31/2012', '2000-07-04', 'Beograd', 'Prvomajska', 19, '0640482056', 'student31@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (32, 'Edwin', 'Hermiston', 'Karina', 'I2 32/2011', '2000-01-20', 'Beograd', 'Tošin bunar', 54, '0640653483', 'student32@gmail.com', 3);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (33, 'Norbert', 'Waters', 'Burton', 'EL 33/2018', '2000-05-23', 'Beograd', 'Bulevar Mihajla Pupina', 33, '0645137654', 'student33@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (34, 'Judson', 'Ratke', 'Jarred', 'E5 34/2020', '2000-07-01', 'Beograd', 'Marka Čelebonovića', 89, '0648185720', 'student34@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (35, 'Leland', 'Morissette', 'Boyce', 'MB 35/2017', '2000-09-13', 'Beograd', 'Vojvođanska', 49, '0640620808', 'student35@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (36, 'Prudence', 'Murphy', 'Jeannetta', 'EE 36/2019', '2000-05-08', 'Beograd', 'Omladinskih brigada', 84, '0649110484', 'student36@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (37, 'Mohammad', 'Champlin', 'Lisabeth', 'ME 37/2019', '2000-06-06', 'Beograd', 'Bulevar vojvode Putnika', 11, '0642133486', 'student37@gmail.com', 3);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (38, 'Dante', 'Goldner', 'Elenor', 'II 38/2014', '2000-07-16', 'Beograd', 'Teodora Drajzera', 17, '0649770272', 'student38@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (39, 'Coretta', 'Torphy', 'Lolita', 'MB 39/2021', '2000-10-06', 'Beograd', 'Sinđelićeva', 53, '0647053524', 'student39@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (40, 'Fredric', 'Kassulke', 'Fernando', 'DU 40/2020', '2000-06-15', 'Beograd', 'Ustanička', 44, '0648783553', 'student40@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (41, 'Irma', 'Denesik', 'Loyd', 'ET 41/2013', '2000-08-04', 'Novi Sad', 'Bulevar cara Lazara', 72, '0640674372', 'student41@gmail.com', 2);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (42, 'Fawn', 'Kautzer', 'Ty', 'ES 42/2013', '2000-06-20', 'Novi Sad', 'Bulevar despota Stefana', 42, '0640112507', 'student42@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (43, 'Nova', 'Gleason', 'Shaniqua', 'XS 43/2019', '2000-02-05', 'Novi Sad', 'Bulevar Evrope', 28, '0641326748', 'student43@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (44, 'Gilberte', 'Shanahan', 'Lorenzo', 'Z3 44/2021', '2000-05-13', 'Novi Sad', 'Bulevar Jaše Tomića', 25, '0641107435', 'student44@gmail.com', 3);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (45, 'Teddy', 'O''Conner', 'Felisha', 'ZU 45/2014', '2000-04-03', 'Novi Sad', 'Bulevar Jovana Dučića', 76, '0648325215', 'student45@gmail.com', 3);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (46, 'Courtney', 'Price', 'Trinidad', 'DV 46/2015', '2000-10-02', 'Novi Sad', 'Bulevar kneza Miloša', 41, '0647667384', 'student46@gmail.com', 0);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (47, 'Catheryn', 'Osinski', 'Homer', 'GE 47/2014', '2000-11-08', 'Novi Sad', 'Bulevar kralja Petra I', 82, '0643412006', 'student47@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (48, 'Maile', 'Greenfelder', 'Weston', 'DB 48/2019', '2000-05-01', 'Novi Sad', 'Bulevar Mihajla Pupina', 55, '0644181778', 'student48@gmail.com', 1);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (49, 'Camie', 'Stokes', 'Ramiro', 'F1 49/2021', '2000-08-22', 'Novi Sad', 'Bulevar oslobođenja', 54, '0640646326', 'student49@gmail.com', 4);
insert into students (id, name, surname, parents_name, index, birth_date, city, street, number, phone, email, year_of_studies) values (50, 'Leigh', 'Nikolaus', 'Jesus', 'M1 50/2016', '2000-10-16', 'Novi Sad', 'Bulevar Patrijarha Pavla', 42, '0646251270', 'student50@gmail.com', 2);
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------- Altering student_id_seq ----------------------------------------------------------------------------------------
alter sequence student_id_seq restart with 51;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------- Inserting users ------------------------------------------------------------------------------------------
insert into users (id, name, surname, username, password) values (1, 'Dean', 'Carter', 'referent1', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (2, 'Xiomara', 'Greenholt', 'referent2', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (3, 'Vanna', 'Wiegand', 'referent3', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (4, 'Virgilio', 'Satterfield', 'referent4', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (5, 'Leonard', 'Klocko', 'referent5', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (6, 'An', 'Konopelski', 'referent6', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (7, 'Basil', 'Thompson', 'referent7', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (8, 'Elsa', 'Moen', 'referent8', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (9, 'Jamal', 'Spencer', 'referent9', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (10, 'Dorsey', 'Johnston', 'referent10', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (11, 'Sol', 'Okuneva', 'referent11', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (12, 'Carin', 'Luettgen', 'referent12', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (13, 'Ismael', 'Kerluke', 'referent13', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (14, 'Orval', 'Spencer', 'referent14', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (15, 'Alethia', 'Cummings', 'referent15', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (16, 'Mohammad', 'Casper', 'referent16', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (17, 'Rickie', 'Senger', 'referent17', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (18, 'Eleanor', 'Collier', 'referent18', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (19, 'Isaiah', 'Bartoletti', 'referent19', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
insert into users (id, name, surname, username, password) values (20, 'Dino', 'Parisian', 'referent20', '$2a$10$JCYrt8QGHg4suBXWiRgjKu93h5DCq3yFDXMDsTY/Itkgeu3h3pCE6');
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------- Altering referent_id_seq ---------------------------------------------------------------------------------------
alter sequence user_id_seq restart with 21;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

